allow unregistering a factory
bancorprotocol/contracts-solidity pull request #583
Opened 2021-04-07 10:58 UTC by barakman

2021-04-08 14:15 UTC, lbeder requested changes

2021-04-08 14:37 UTC, barakman commented on solidity/contracts/converter/ConverterFactory.sol
> +        converterFactories[converterType] = ITypedConverterFactory(0);
fixed

2021-04-08 14:38 UTC, barakman commented on solidity/contracts/helpers/TestTypedConverterCustomFactory.sol
> +import "../converter/interfaces/ITypedConverterCustomFactory.sol";
fixed

2021-04-08 14:47 UTC, barakman commented on solidity/contracts/converter/ConverterFactory.sol
> +     * @dev registers a specific typed converter factory
fixed

2021-04-08 14:51 UTC, barakman commented on solidity/contracts/converter/ConverterFactory.sol
> +    function unregisterTypedConverterFactory(ITypedConverterFactory _factory) public ownerOnly {
fixed

2021-04-08 16:19 UTC, lbeder commented on solidity/contracts/converter/ConverterFactory.sol
> +     * @dev registers a specific typed converter factory
💪

2021-04-08 16:19 UTC, lbeder commented on solidity/contracts/converter/ConverterFactory.sol
> +    function unregisterTypedConverterFactory(ITypedConverterFactory _factory) public ownerOnly {
💪

2021-04-08 16:21 UTC, lbeder commented on solidity/contracts/converter/ConverterFactory.sol
> +     * @dev registers a specific typed converter factory
Thanks for going over it. There are only two changes left:
1. State variables should be only `private` (and explicit getters need to be added if/where required).
2. There's no need for padding argument descriptions in the NATSPEC.

2021-04-09 04:26 UTC, barakman commented on solidity/contracts/converter/ConverterFactory.sol
> +     * @dev registers a specific typed converter factory
done

2021-04-09 14:34 UTC, lbeder approved these changes
Nice job! 👍

2021-04-09 15:18 UTC, merged